{
  "name": "youtube-playlist-extractor-api",
  "version": "1.0.0",
  "description": "API para extraer videos de playlists de YouTube usando Selenium",
  "main": "app.py",
  "scripts": {
    "start": "gunicorn app:app"
  },
  "buildpacks": [
    {
      "url": "https://github.com/heroku/heroku-buildpack-google-chrome"
    },
    {
      "url": "https://github.com/heroku/heroku-buildpack-chromedriver"
    },
    {
      "url": "heroku/python"
    }
  ]
}
